[[buildpacks]]
id = "dev.boson.rust"
uri = "docker://quay.io/boson/faas-rust-bp:{{VERSION}}"

[[order]]
[[order.group]]
id = "dev.boson.rust"

[stack]
id = "dev.boson.stacks.rust"
build-image = "quay.io/boson/faas-stack-build:rust-{{VERSION}}"
run-image = "quay.io/boson/faas-stack-run:rust-{{VERSION}}"

[lifecycle]
uri = "file://lifecycle/lifecycle-v0.13.0+linux.x86-64.tgz"
