# Buildpacks to include in builder
[[buildpacks]]
id = "dev.boson.nodejs"
image = "quay.io/boson/faas-nodejs-bp:{{VERSION}}"

[[buildpacks]]
id = "dev.boson.typescript"
image = "quay.io/boson/faas-typescript-bp:{{VERSION}}"

[[order]]
  [[order.group]]
  id = "dev.boson.nodejs"
  [[order.group]]
  id = "dev.boson.typescript"

# Stack that will be used by the builder
[stack]
id = "dev.boson.stacks.nodejs"
# This image is used at runtime
run-image = "quay.io/boson/faas-stack-run:nodejs-{{VERSION}}"
# This image is used at build-time
build-image = "quay.io/boson/faas-stack-build:nodejs-{{VERSION}}"
