# Buildpacks to include in builder
[[buildpacks]]
id = "com.redhat.faas.nodejs"
image = "quay.io/boson/faas-nodejs-bp"

[[order]]
[[order.group]]
id = "com.redhat.faas.nodejs"

# Stack that will be used by the builder
[stack]
    id = "com.redhat.faas.stacks.nodejs"
    # This image is used at runtime
    run-image = "quay.io/boson/faas-stack-run:nodejs"
    # This image is used at build-time
    build-image = "quay.io/boson/faas-stack-build:nodejs"