# Buildpacks to include in builder
[[buildpacks]]
id = "dev.boson.nodejs"
image = "quay.io/boson/faas-nodejs-bp:{{VERSION}}"

[[buildpacks]]
id = "dev.boson.typescript"
image = "quay.io/boson/faas-typescript-bp:{{VERSION}}"

[[order]]
  [[order.group]]
  id = "dev.boson.nodejs"
  [[order.group]]
  id = "dev.boson.typescript"
  optional = true

# Stack that will be used by the builder
[stack]
id = "com.redhat.stacks.ubi8-nodejs-14"
# This image is used at runtime
run-image =   "registry.access.redhat.com/ubi8/nodejs-14-minimal"
# This image is used at build-time
build-image = "registry.access.redhat.com/ubi8/nodejs-14"
