# Buildpacks to include in builder
[[buildpacks]]
id = "dev.boson.springboot"
image = "quay.io/boson/faas-springboot-bp:{{VERSION}}"

[[order]]
[[order.group]]
id = "dev.boson.springboot"

# Stack that will be used by the builder
[stack]
id = "dev.boson.stacks.springboot"
# This image is used at runtime
run-image = "quay.io/boson/faas-stack-run:springboot-{{VERSION}}"
# This image is used at build-time
build-image = "quay.io/boson/faas-stack-build:springboot-{{VERSION}}"
