# Buildpacks to include in builder
[[buildpacks]]
id = "dev.boson.quarkus-native"
uri = "docker://quay.io/boson/faas-quarkus-native-bp:{{VERSION}}"

[[order]]
[[order.group]]
id = "dev.boson.quarkus-native"

# Stack that will be used by the builder
[stack]
id = "dev.boson.stacks.quarkus-native"
# This image is used at runtime
run-image = "quay.io/boson/faas-stack-run:quarkus-native-{{VERSION}}"
# This image is used at build-time
build-image = "quay.io/boson/faas-stack-build:quarkus-native-{{VERSION}}"
