# Buildpacks to include in builder
[[buildpacks]]
id = "com.redhat.faas.quarkus"
image = "quay.io/boson/faas-quarkus-bp:{{VERSION}}"

[[order]]
[[order.group]]
id = "com.redhat.faas.quarkus"

# Stack that will be used by the builder
[stack]
    id = "com.redhat.faas.stacks.quarkus"
    # This image is used at runtime
    run-image = "quay.io/boson/faas-stack-run:quarkus-{{VERSION}}"
    # This image is used at build-time
    build-image = "quay.io/boson/faas-stack-build:quarkus-{{VERSION}}"
