[[buildpacks]]
id = "com.redhat.faas.go"
image = "quay.io/boson/faas-go-bp"

[[order]]
[[order.group]]
id = "com.redhat.faas.go"

[stack]
    id = "com.redhat.faas.stacks.go"
    build-image = "quay.io/boson/faas-stack-build:go"
    run-image = "quay.io/boson/faas-stack-run:go"
