[[buildpacks]]
id = "dev.boson.go"
image = "quay.io/boson/faas-go-bp:{{VERSION}}"

[[order]]
[[order.group]]
id = "dev.boson.go"

[stack]
id = "dev.boson.stacks.go"
build-image = "quay.io/boson/faas-stack-build:go-{{VERSION}}"
run-image = "quay.io/boson/faas-stack-run:go-{{VERSION}}"
