name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.9.3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Determine download URL for latest pack
        id: pack-download-url
        uses: actions/github-script@v2
        with:
          result-encoding: string
          script: |
            return github.repos.getReleaseByTag({
                owner: "buildpacks",
                repo: "pack",
                tag: "v0.18.1"
            }).then(result => {
                return result.data.assets
                  .filter(a => a.name.includes("linux"))
                  .map(a => a.browser_download_url)[0];
            })

      - name: Install pack
        run: |
          curl -s -L -o pack.tgz ${{ steps.pack-download-url.outputs.result }}
          tar -xvf pack.tgz

      - name: Build
        run: PACK_CMD="$(pwd)/pack" make

      - name: Install func
        run: make bin/func_stable && make bin/func_snapshot

      - name: Test
        run: PACK_CMD="$(pwd)/pack" make test

      - name: Push Images
        if: ${{ steps.release.outputs.release_created }}
        env:
          USER: ${{ secrets.QUAY_USER }}
          PASS: ${{ secrets.QUAY_TOKEN }}
        run: docker login -u "$USER" -p "$PASS" quay.io && make publish
