name: CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2.9.3
        if: ${{ github.ref == 'refs/heads/main' }}
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - uses: buildpacks/github-actions/setup-pack@v4.1.0
        with:
          pack-version: 0.23.0

      - name: Build
        run: make

      - name: Install func
        run: make bin/func_stable && make bin/func_snapshot

      - name: Test
        run: make test

      - name: Push Images
        if: ${{ steps.release.outputs.release_created }}
        env:
          USER: ${{ secrets.QUAY_USER }}
          PASS: ${{ secrets.QUAY_TOKEN }}
        run: docker login -u "$USER" -p "$PASS" quay.io && make publish
