# Deploy artifacts for any pushes with a version tag (releases).
name: Releases

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Determine download URL for latest pack
        id: pack-download-url
        uses: actions/github-script@v2
        with:
          result-encoding: string
          script: |
            return github.repos.getLatestRelease({
                owner: "buildpacks",
                repo: "pack"
            }).then(result => {
                return result.data.assets
                  .filter(a => a.name.includes("linux"))
                  .map(a => a.browser_download_url)[0];
            })
      - name: Install pack
        run: |
          curl -s -L -o pack.tgz ${{ steps.pack-download-url.outputs.result }}
          tar -xvf pack.tgz

      - uses: azure/docker-login@v1
        with:
          login-server: quay.io
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build
        run: PACK_CMD=./pack make

      - name: Deploy
        run: make publish
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
      - name: Test
        run:  make test
      - name: Build
        run:  make build
      - name: Image
        run:  make image
      - name: Push Image
        env:
          USER: ${{ secrets.QUAY_USERNAME }}
          PASS: ${{ secrets.QUAY_PASSWORD }}
        run: docker login -u "$USER" -p "$PASS" quay.io && make push

        # TODO: make release
        # - build cross-platform binaries
        # - create a release with assets
